services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  grafana:
    image: grafana/otel-lgtm:latest
    ports:
      - "3000:3000"
      - "4318:4318"
      - "4319:4319"
