services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  grafana:
    image: grafana/grafana:12.3.3
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      mimir:
        condition: service_healthy
      loki:
        condition: service_healthy
      tempo:
        condition: service_healthy
    ports:
      - "3000:3000"

  mimir:
    image: grafana/mimir:3.0.3
    command: [ "-config.file=/etc/mimir/mimir.yaml", "-target=all" ]
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir/mimir.yaml:ro
    healthcheck:
      test: [ "CMD", "/bin/mimir", "-version" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    ports:
      - "9009:9009"

  loki:
    image: grafana/loki:3.6.7
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-version" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:2.10.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml:ro
    healthcheck:
      test: [ "CMD", "/tempo", "-version" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
