spring.application.name=cart-service
server.port=9003

store.urls.item=http://localhost:9001

management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.opentelemetry.resource-attributes.service.instance.id=${HOSTNAME:local-dev}

management.otlp.metrics.export.url=http://localhost:4318/v1/metrics

management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces

management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs
management.opentelemetry.instrumentation.logback-appender.capture-experimental-attributes=true
management.opentelemetry.instrumentation.logback-appender.capture-key-value-pair-attributes=true
