spring.application.name=store
server.port=9000

store.urls.item=http://localhost:9001
store.urls.stock=http://localhost:9002
store.urls.cart=http://localhost:9003
store.urls.order=http://localhost:9005

management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.opentelemetry.resource-attributes.service.instance.id=${HOSTNAME:local-dev}

management.otlp.metrics.export.url=http://localhost:4318/v1/metrics

management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces

management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs
management.opentelemetry.instrumentation.logback-appender.capture-experimental-attributes=true
management.opentelemetry.instrumentation.logback-appender.capture-key-value-pair-attributes=true
